package model;
// Generated Jun 11, 2021 12:34:56 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlTransient;




/**
 * Categorie generated by hbm2java
 */
public class Categorie  implements java.io.Serializable {


     private int id;
     private String intitule;
        //  @OneToMany(mappedBy = "idCategorie")
    
     private List<Produits> produitsList = new ArrayList<Produits>() ;

    public Categorie() {
    }

	
    public Categorie(int id) {
        this.id = id;
    }
    public Categorie(int id, String intitule) {
       this.id = id;
       this.intitule = intitule;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }
    
   @OneToMany(targetEntity=Produits.class,cascade = CascadeType.ALL, 
              fetch = FetchType.LAZY, orphanRemoval = true)
    public List<Produits> getProduitsList() {
        return produitsList;
    }

    public void setProduitsList(List<Produits> produitsList) {
        this.produitsList = produitsList;
    }





}


