package model;
// Generated Jun 11, 2021 12:34:56 PM by Hibernate Tools 4.3.1

import dao.ProduitDAO;




/**
 * Commandes generated by hbm2java
 */
public class Commandes  implements java.io.Serializable {


     private int id;
     private Integer idProduit;
     private Integer idUser;
     private Integer qte;
     
     private Produits prod; 

    public Commandes() {
       
    }

	
    public Commandes(int id) {
        this.id = id;
    }
    
     public Commandes(Integer idProduit, Integer qte) {
       this.idProduit = idProduit;
       this.qte = qte;
        prod=(new ProduitDAO()).recuperer(idProduit);
    }
    public Commandes(int id, Integer idProduit, Integer idUser, Integer qte) {
       this.id = id;
       this.idProduit = idProduit;
       this.idUser = idUser;
       this.qte = qte;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(Integer idProduit) {
        this.idProduit = idProduit;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Integer getQte() {
        return this.qte;
    }
    
    public void setQte(Integer qte) {
        this.qte = qte;
    }
    
    public Produits getProd(){
        return prod;
    }
    
    public void setProd(Produits prod)
    {
        this.prod=prod;
    }




}


