package model;
// Generated Jun 11, 2021 12:34:56 PM by Hibernate Tools 4.3.1


import java.util.List;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;




/**
 * Produits generated by hbm2java
 */
public class Produits  implements java.io.Serializable {


     private int id;
     private String nom;
     private Integer idCategorie;
     private Integer qteDisponible;
     private Integer prix;
     private String imgLink;
     
     
    
    @JoinColumn(name = "ID_CATEGORIE", referencedColumnName = "ID")
    @ManyToOne
    private Categorie cat = new Categorie();

    public Produits() {
    }

	
    public Produits(int id) {
        this.id = id;
    }
    public Produits(int id, String nom, Integer idCategorie, Integer qteDisponible, Integer prix, String imgLink) {
       this.id = id;
       this.nom = nom;
       this.idCategorie = idCategorie;
       this.qteDisponible = qteDisponible;
       this.prix = prix;
       this.imgLink = imgLink;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Integer getIdCategorie() {
        return this.idCategorie;
    }
    
    public void setIdCategorie(Integer idCategorie) {
        this.idCategorie = idCategorie;
    }
    public Integer getQteDisponible() {
        return this.qteDisponible;
    }
    
    public void setQteDisponible(Integer qteDisponible) {
        this.qteDisponible = qteDisponible;
    }
    public Integer getPrix() {
        return this.prix;
    }
    
    public void setPrix(Integer prix) {
        this.prix = prix;
    }
    public String getImgLink() {
        return this.imgLink;
    }
    
    public void setImgLink(String imgLink) {
        this.imgLink = imgLink;
    }

    public Categorie getCat() {
        return cat;
    }

    public void setCat(Categorie cat) {
        this.cat = cat;
    }


    

}


