package model;
// Generated Jun 11, 2021 12:34:56 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String name;
     private String password;

    public Users() {
    }

	
    public Users(int id) {
        this.id = id;
    }
    public Users(int id, String name, String password) {
       this.id = id;
       this.name = name;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


